# SPDX-FileCopyrightText: 2023, 2024 Horus View and Explore B.V.
#
# SPDX-License-Identifier: MIT

"""Add Service table.

Revision ID: 377f052dc735
Revises: e47930380209
Create Date: 2023-09-14 15:53:48.227041

"""
from alembic import op
import sqlalchemy as sa

import mercaido_server.models.types


# revision identifiers, used by Alembic.
revision = '377f052dc735'
down_revision = 'e47930380209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('ident', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('data', mercaido_server.models.types.ServiceMessageColumnType(), nullable=False),
    sa.PrimaryKeyConstraint('ident', name=op.f('pk_services'))
    )
    # op.alter_column('jobs', 'started_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('jobs', 'finished_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('jobs', 'error_msg',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('jobs', 'error_msg',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('jobs', 'finished_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # op.alter_column('jobs', 'started_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    op.drop_table('services')
    # ### end Alembic commands ###
