# SPDX-FileCopyrightText: 2023, 2024 Horus View and Explore B.V.
#
# SPDX-License-Identifier: MIT

"""Job model

Revision ID: af2d025ce718
Revises: 8a2e9175ee3d
Create Date: 2023-07-21 10:55:34.871198

"""
from alembic import op
import sqlalchemy as sa

from mercaido_server.models.job import readable_id

# revision identifiers, used by Alembic.
revision = "af2d025ce718"
down_revision = "8a2e9175ee3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            sa.String(47),
            nullable=False,
            primary_key=True,
            default=lambda: readable_id(),
        ),
        sa.Column("service_id", sa.String(255), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Boolean(), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    # ### end Alembic commands ###
