"""Add FeatureServer model

Revision ID: 230c147444f1
Revises: 377f052dc735
Create Date: 2024-05-30 10:46:41.730566

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "230c147444f1"
down_revision = "377f052dc735"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_servers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_servers")
    # ### end Alembic commands ###
